import type { Metadata } from "next";

import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Navbar from "@/component/Navbar";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme"; 
import localFont from 'next/font/local'

const myfont = localFont({ src:'../../public/assets/fonts/IRANSansXV.woff2'})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout=({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)=> {
  return (
    <html lang="en" dir="rtl"  className={myfont.className}>
      <body >
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <Navbar></Navbar>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  
  );
}

export default RootLayout